### ISSUE TITLE
same line, same font ..why separated ?  

### ISSUE THREAD

**Issue by kieregh** [ChrizH/pdfstructure#2]
![pdf_structured_q](https://user-images.githubusercontent.com/5086827/107335236-09e0e000-6afb-11eb-8dcd-6d6444bb5650.gif)

**Comment by ChrizH** [comment]
Hi, can you provide the tested PDF?

**Comment by kieregh** [comment]
I attached the PDF as follow.

[pdf_sample.pdf](https://github.com/ChrizH/pdfstructure/files/5952394/pdf_sample.pdf)

**Comment by ChrizH** [comment]
pdfminer's `high_level.extract_pages()` method is used to get the raw pages and their text boxes from a PDF.

Example: The flat text box list for page 7 looks like:
![Screenshot 2021-02-09 at 20 41 06](https://user-images.githubusercontent.com/3228560/107418633-2c80f200-6b17-11eb-8942-03ca9b7f99ac.png)

It seems like `\n` new line characters are recognised wrongly on many places. Not sure yet how to fix that issue (its related to how pdfminer extracts text)
