### ISSUE TITLE
Wrong text order

### ISSUE THREAD

**Issue by bogdankostic** [ChrizH/pdfstructure#3]
First of all, thanks for this project! On some of my pdf Documents, the exact hierarchical document structure was extracted.

Unfortunately, the result was not that good for some documents, especially for multi-column docs. For example, when I want to get the structure of [this doc](https://arxiv.org/pdf/2004.04906.pdf), the text order is quite messed up. Do you plan to fix this to support different types of documents?

**Comment by ChrizH** [comment]
Hi @bogdankostic, thank you for your feedback!
I have planned to detect automatically a document's layout and optimise the `LAParams` accordingly.. 
but for now I have pushed a [commit](https://github.com/ChrizH/pdfstructure/commit/59aadba2b2e0b530af600356c0271503c37f0b1a) that improves support for column-based documents per default (less performant though)

```
source = FileSource(file_path, la_params=LAParams(boxes_flow=0.3, detect_vertical=True))
parser.parse_pdf(source)
```

If no advanced column-based analysis is needed, one can simply disable it with.
```
FileSource(file_path, la_params=LAParams(boxes_flow=None, detect_vertical=False))
```

Output for your example:
[Dense_Passage_Retrieval.txt](https://github.com/ChrizH/pdfstructure/files/6006123/Dense_Passage_Retrieval.txt)
